create table if not exists public.dorsal_hand_tracking_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tracking_enabled boolean not null default false,
  baseline_predicted_age numeric(5, 1),
  baseline_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.dorsal_hand_predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  assessment_id text,
  predicted_at timestamptz not null default now(),
  predicted_age numeric(5, 1) not null,
  confidence numeric(5, 4) not null,
  age_bins jsonb not null default '{}'::jsonb,
  model_name text not null default 'dorsal',
  source text not null,
  is_baseline boolean not null default false
);

create index if not exists dorsal_hand_predictions_user_date_idx
  on public.dorsal_hand_predictions (user_id, predicted_at);

alter table public.dorsal_hand_tracking_profiles enable row level security;
alter table public.dorsal_hand_predictions enable row level security;
